# Generated by Django 5.0 on 2024-02-14 11:16

import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='EditorGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_text', models.TextField(blank=True, help_text='Add a leading information paragraph explaining the guide')),
                ('sections', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title', icon='title', template='wagtail_guide/streamfield/blocks/heading_block.html')), ('paragraph', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'link', 'ul', 'ol', 'hr'])), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.CharBlock(required=False))])), ('quote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.CharBlock(form_classname='title')), ('attribution', wagtail.blocks.CharBlock(required=False))])), ('pull_quote', wagtail.blocks.StructBlock([('pull_quote', wagtail.blocks.CharBlock(form_classname='title'))])), ('embed', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('embed', wagtail.embeds.blocks.EmbedBlock())])), ('video', wagtail.blocks.StructBlock([('video', wagtail.embeds.blocks.EmbedBlock(label='Video URL', required=False))]))], blank=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Manage Editor Guide',
            },
        ),
    ]
