# Generated by Django 4.2.5 on 2023-12-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_guide', '0002_alter_editorguide_sections_w30_usejsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorguide',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
